<a href="https://colab.research.google.com/github/oshaajayaweera/Databases-and-Analytics/blob/main/01_SQL_in_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
install.packages("sqldf")
install.packages("dplyr")
install.packages("ggplot2")

library(sqldf)
library(dplyr)
library(ggplot2)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
base_url <- "https://raw.githubusercontent.com/oshaajayaweera/Databases-and-Analytics/main/"

customers <- read.csv(paste0(base_url, "customers.csv"))
orders <- read.csv(paste0(base_url, "orders.csv"))
deliveries <- read.csv(paste0(base_url, "deliveries.csv"))
drivers <- read.csv(paste0(base_url, "drivers.csv"))
vehicles <- read.csv(paste0(base_url, "vehicles.csv"))
hubs <- read.csv(paste0(base_url, "hubs.csv"))
complaints <- read.csv(paste0(base_url, "complaints.csv"))
incidents <- read.csv(paste0(base_url, "incidents.csv"))
app_events <- read.csv(paste0(base_url, "app_events.csv"))
data_dictionary <- read.csv(paste0(base_url, "data_dictionary.csv"))

In [3]:
head(deliveries)
str(deliveries)
head(orders)
head(hubs)

  delivery_id order_id driver_id vehicle_id hub_id dispatch_time
1 DL00001     O00938   D004      V056       H05    2024-06-18 10:57:00
2 DL00002     O00004   D138      V007       H02    2025-01-11 18:45:00
3 DL00003     O00639   D006      V049       H02    2025-06-02 20:39:00
4 DL00004     O00313   D116      V055       H02    2024-03-08 23:31:00
5 DL00005     O00844   D108      V034       H01    2025-09-21 11:43:00
6 DL00006     O00029   D037      V098       H03    2024-09-11 12:40:00
  delivery_completed_at      delivery_status route_distance_km
1 2024-06-19 09:05:59.904311 Failed          17.26
2 2025-01-11 17:39:00.000000 OnTime          10.34
3 2025-06-02 21:45:32.366770 OnTime           7.92
4 2024-03-09 23:30:08.103702 Delayed         16.42
5 2025-09-21 15:45:34.131056 OnTime          14.52
6 2024-09-12 17:11:52.384869 Delayed         13.84
  manual_route_override_count proof_of_completion_missing
1 1                           0
2 1                           0
3 0                           0
4 0                           0
5 1                           0
6 0                           0
  customer_rating_post_delivery fuel_or_charge_cost
1 3.07                          12.05
2 5.00                          13.41
3 4.98                           8.51
4 4.18                          13.62
5 4.18                           9.22
6 1.57                           9.58

'data.frame':	950 obs. of  13 variables:
 $ delivery_id                  : chr  "DL00001" "DL00002" "DL00003" "DL00004" ...
 $ order_id                     : chr  "O00938" "O00004" "O00639" "O00313" ...
 $ driver_id                    : chr  "D004" "D138" "D006" "D116" ...
 $ vehicle_id                   : chr  "V056" "V007" "V049" "V055" ...
 $ hub_id                       : chr  "H05" "H02" "H02" "H02" ...
 $ dispatch_time                : chr  "2024-06-18 10:57:00" "2025-01-11 18:45:00" "2025-06-02 20:39:00" "2024-03-08 23:31:00" ...
 $ delivery_completed_at        : chr  "2024-06-19 09:05:59.904311" "2025-01-11 17:39:00.000000" "2025-06-02 21:45:32.366770" "2024-03-09 23:30:08.103702" ...
 $ delivery_status              : chr  "Failed" "OnTime" "OnTime" "Delayed" ...
 $ route_distance_km            : num  17.26 10.34 7.92 16.42 14.52 ...
 $ manual_route_override_count  : int  1 1 0 0 1 0 0 1 1 1 ...
 $ proof_of_completion_missing  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ customer_rating_post_delivery: num  3.07 5 4.98 4.18 4.18 1.57 4.64 3.76 3.7 3.2 ...
 $ fuel_or_charge_cost          : num  12.05 13.41 8.51 13.62 9.22 ...

  order_id customer_id service_type order_created_at    promised_window_hours
1 O00001   C0292       Passenger    2024-08-20 14:43:00  6
2 O00002   C0459       Passenger    2024-05-14 22:16:00 24
3 O00003   C0161       Passenger    2025-09-02 14:37:00  4
4 O00004   C0520       Parcel       2025-01-11 17:15:00  2
5 O00005   C0558       Retail       2025-02-17 19:32:00 12
6 O00006   C0437       Retail       2024-08-05 04:55:00  1
  pickup_zone dropoff_zone priority_level order_value booking_channel
1 Airport     South        Medium         126.65      App
2 North       AIRPORT      Low            109.30      App
3 West        AIRPORT      High            33.50      Phone
4 RiverSide   North        Medium          10.04      App
5 Riverside   SOUTH        Low            125.58      Phone
6 CENTRAL     East         High           151.44      Web
  special_handling_flag
1 0
2 0
3 0
4 1
5 0
6 1

  hub_id hub_name       zone    hub_type  capacity_score
1 H01    North Exchange North   Dispatch  82
2 H02    South Link     South   Dispatch  78
3 H03    East Dock      East    Warehouse 74
4 H04    West Gate      West    Dispatch  69
5 H05    Central Core   Central Control   88
6 H06    Airport Hub    Airport Dispatch  71